Repository BinaryStudioAcademy/bsa-2020-schedulia, pull requests merged in 2020-08, with the labels that each got.

#49 Add prefix 'v1' to the API
  api/app/Providers/RouteServiceProvider.php
  api/routes/api.php
  client/.env.example
  client/src/services/status/statusService.js
Labels: enhancement

#51 Add http methods to request service
  client/src/services/requestService.js
Labels: enhancement

#56 Add auth state
  client/src/services/auth/authService.js
  client/src/store/index.js
  client/src/store/modules/auth/actions.js
  client/src/store/modules/auth/getters.js
  client/src/store/modules/auth/index.js
  client/src/store/modules/auth/mutations.js
  client/src/store/modules/auth/state.js
  client/src/store/modules/auth/types/actions.js
  client/src/store/modules/auth/types/getters.js
  client/src/store/modules/auth/types/mutations.js
Labels: enhancement

#66 Add user data provider
  client/src/components/guard/UserDataProvider.vue
  client/src/router/index.js
  client/src/services/auth/authService.js
  client/src/store/modules/auth/actions.js
  client/src/store/modules/auth/getters.js
  client/src/store/modules/auth/mutations.js
  client/src/store/modules/auth/state.js
  client/src/store/modules/auth/types/getters.js
  client/src/store/modules/auth/types/mutations.js
Labels: enhancement

#68 Feature/user profile tabs
  client/src/App.vue
  client/src/components/profile/BrandingForm.vue
  client/src/components/profile/LoginForm.vue
  client/src/components/profile/ProfileForm.vue
  client/src/components/profile/UserProfile.vue
  client/src/components/tabs/Tabs.vue
  client/src/router/index.js
  client/src/views/Profile.vue
Labels: enhancement

#72 Add LoginGuard
  client/src/components/guard/LoginGuard.vue
  client/src/router/index.js
Labels: enhancement

#75 Feature/user profile login form
  client/src/components/profile/ChangePasswordForm.vue
  client/src/components/profile/LoginForm.vue
  client/src/components/tabs/Tabs.vue
Labels: enhancement

#84 Feature/add signup component
  client/src/components/alert/Alert.vue
  client/src/components/auth/SignUp.vue
  client/src/plugins/vuetify.js
  client/src/store/modules/i18n/en.js
Labels: enhancement

#90 Feature/user profile brnading form
  client/src/assets/images/no-image.png
  client/src/components/profile/BrandingForm.vue
  client/src/components/profile/ChangePasswordForm.vue
  client/src/components/tooltip/TooltipIcon.vue
  client/src/services/profile/profileService.js
  client/src/services/upload/fileService.js
  client/src/store/index.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/profile/actions.js
  client/src/store/modules/profile/getters.js
  client/src/store/modules/profile/index.js
  client/src/store/modules/profile/mutations.js
  client/src/store/modules/profile/state.js
  client/src/store/modules/profile/types/mutations.js
Labels: enhancement

#93 Fix/fix layout and signup component
  client/src/components/auth/Login.vue
  client/src/components/auth/SignUp.vue
  client/src/store/modules/i18n/en.js
Labels: fix

#113 Feature/add userlogo in header
  client/src/components/common/GeneralLayout/Avatar.vue
Labels: enhancement

#112 Add a link to the profile page in the drop down menu of header
  client/src/components/common/GeneralLayout/UserMenu.vue
Labels: enhancement

#119 Feature/add event public page api
  api/app/Actions/Event/AddEventAction.php
  api/app/Actions/Event/AddEventRequest.php
  api/app/Entity/Event.php
  api/app/Http/Controllers/Api/EventController.php
  api/app/Http/Requests/Api/Event/EventRequest.php
  api/app/Repositories/Event/EventRepository.php
  api/app/Repositories/Event/EventRepositoryInterface.php
  api/database/migrations/2020_08_10_194722_transform_start_date_to_timestamp.php
Labels: enhancement

#115 add profile fields to user table
  api/database/factories/UserFactory.php
  api/database/migrations/2020_08_10_213857_add_profile_fields_to_users_table.php
  api/tests/Feature/Auth/RegistrationTest.php
Labels: enhancement

#120 Feature/add event public page api
  api/app/Actions/Event/AddEventAction.php
  api/app/Events/EventCreated.php
  api/app/Listeners/SendEventCreatedNotification.php
  api/app/Mail/EventCreatedMail.php
  api/app/Notifications/EventCreatedNotification.php
  api/app/Providers/EventServiceProvider.php
  api/resources/views/notifications/event_created.blade.php
  api/routes/channels.php
Labels: enhancement

#121 Feature/profile endpoints
  api/app/Actions/User/UpdateUserAction.php
  api/app/Actions/User/UpdateUserRequest.php
  api/app/Actions/User/UpdateUserResponse.php
  api/app/Exceptions/User/UserNotFoundException.php
  api/app/Http/Controllers/Api/UserController.php
  api/app/Http/Presenters/UserArrayPresenter.php
  api/app/Http/Requests/Api/User/UpdateUserRequest.php
  api/database/factories/UserFactory.php
  api/routes/api.php
  api/tests/Feature/User/UpdateApiTest.php
Labels: enhancement

#133 Fix eventRequest validation
  api/app/Http/Requests/Api/Event/EventRequest.php
Labels: fix

#111 Feature/user profile main form
  client/src/components/profile/BrandingForm.vue
  client/src/components/profile/LoginForm.vue
  client/src/components/profile/ProfileForm.vue
  client/src/components/profile/ProfileSelect.vue
  client/src/components/profile/ProfileTextArea.vue
  client/src/components/profile/ProfileTextField.vue
  client/src/components/profile/UserProfile.vue
  client/src/components/tabs/Tabs.vue
  client/src/services/profile/profileService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/profile/actions.js
  client/src/store/modules/profile/getters.js
  client/src/store/modules/profile/mutations.js
  client/src/store/modules/profile/state.js
  client/src/store/modules/profile/types/mutations.js
  client/src/views/Profile.vue
Labels: enhancement

#138 Feature/file uploader
  api/app/Actions/Upload/UploadImageAction.php
  api/app/Actions/Upload/UploadImageRequest.php
  api/app/Actions/Upload/UploadImageResponse.php
  api/app/Contracts/FileUploader.php
  api/app/Http/Controllers/Api/UploadController.php
  api/app/Http/Presenters/ProfileImagePresenter.php
  api/app/Services/ImageUploader.php
  api/config/filesystems.php
  api/routes/api.php
  api/tests/Feature/Upload/UploadFileApiTest.php
  api/tests/Feature/Upload/testFiles/binary-academy.png
Labels: enhancement

#168 Feature/user profile change password
  client/src/components/confirm/ConfirmDialog.vue
  client/src/components/profile/ChangePasswordForm.vue
  client/src/components/profile/LoginForm.vue
  client/src/components/profile/ProfileForm.vue
  client/src/components/profile/UserProfile.vue
  client/src/services/profile/profileService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/profile/actions.js
Labels: enhancement

#170 Feature/delete user profile backend
  api/app/Actions/Upload/UploadImageResponse.php
  api/app/Actions/User/DeleteUserAction.php
  api/app/Actions/User/DeleteUserRequest.php
  api/app/Entity/User.php
  api/app/Http/Controllers/Api/UserController.php
  api/app/Http/Presenters/ProfileImagePresenter.php
  api/app/Http/Presenters/UserArrayPresenter.php
  api/app/Services/ImageUploader.php
  api/routes/api.php
  api/tests/Feature/Upload/UploadFileApiTest.php
  api/tests/Feature/User/DeleteApiTest.php
  api/tests/Feature/User/UpdateApiTest.php
Labels: enhancement

#175 Upload image request
  api/app/Http/Controllers/Api/UploadController.php
  api/app/Http/Requests/Api/Uploader/UploadImageRequest.php
Labels: bug

#171 change password
  api/app/Actions/User/UpdateUserPasswordAction.php
  api/app/Actions/User/UpdateUserPasswordRequest.php
  api/app/Exceptions/BaseException.php
  api/app/Exceptions/ErrorCode.php
  api/app/Exceptions/Handler.php
  api/app/Exceptions/User/UserInvalidPasswordException.php
  api/app/Http/Controllers/Api/UserController.php
  api/app/Http/Requests/Api/User/UpdateUserPasswordRequest.php
  api/routes/api.php
  api/tests/Feature/User/UpdatePasswordApiTest.php
Labels: enhancement

#178 Hotfix/user password action
  client/src/components/profile/ChangePasswordForm.vue
  client/src/services/profile/profileService.js
  client/src/store/modules/profile/actions.js
Labels: fix

#177 timezone select with GMT
  client/src/components/common/form/TimeZoneSelect.vue
  client/src/components/profile/ProfileForm.vue
Labels: fix

#183 add nickname frontend
  client/src/components/profile/ProfileForm.vue
  client/src/store/modules/i18n/en.js
Labels: enhancement

#182 add nickname
  api/app/Actions/Auth/RegisterAction.php
  api/app/Actions/User/UpdateUserAction.php
  api/app/Actions/User/UpdateUserRequest.php
  api/app/Http/Controllers/Api/UserController.php
  api/app/Http/Presenters/UserArrayPresenter.php
  api/app/Http/Requests/Api/User/UpdateUserRequest.php
  api/database/factories/UserFactory.php
  api/database/migrations/2020_08_19_092627_add_nickname_to_users_table.php
Labels: enhancement

#184 altering existing users on migration
  api/database/migrations/2020_08_19_092627_add_nickname_to_users_table.php
Labels: bug

#196 calendar connections layout
  client/src/components/calendar-connections/CalendarsList.vue
  client/src/components/calendar-connections/ConnectedCalendars.vue
  client/src/components/calendar-connections/ConnectedList.vue
  client/src/components/common/GeneralLayout/UserMenu.vue
  client/src/router/index.js
  client/src/store/modules/i18n/en.js
  client/src/views/CalendarConnections.vue
Labels: enhancement

#187 ApiToken Entity
  api/app/Entity/ApiToken.php
  api/app/Entity/SocialAccount.php
  api/app/Entity/User.php
  api/database/migrations/2020_08_19_162718_create_api_tokens_table.php
  api/database/migrations/2020_08_20_212824_remove_service_from_api_token_table.php
  api/database/migrations/2020_08_20_213138_add_social_accounts_table.php
Labels: enhancement

#222 Change link on logo
  client/src/components/common/GeneralLayout/Logo.vue
Labels: fix

#226 Fix background
  client/src/components/tabs/Tabs.vue
Labels: fix, frontend

#229 Feature/confirm email page
  client/src/components/auth/VerifiedEmailComponent.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/views/VerifiedEmail.vue
Labels: fix, frontend

#230 Add pagination for EventTypes
  api/app/Actions/EventType/GetEventTypeCollectionAction.php
  api/app/Actions/EventType/GetEventTypeCollectionRequest.php
  api/app/Actions/PaginatedResponse.php
  api/app/Contracts/PresenterCollectionInterface.php
  api/app/Contracts/PresenterInterface.php
  api/app/Http/Controllers/Api/ApiController.php
  api/app/Http/Controllers/Api/EventTypeController.php
  api/app/Http/Presenters/AuthenticationResponseArrayPresenter.php
  api/app/Http/Presenters/AvailabilityArrayPresenter.php
  api/app/Http/Presenters/AvailabilityServicePresenter.php
  api/app/Http/Presenters/EventTypePresenter.php
  api/app/Http/Presenters/ProfileImagePresenter.php
  api/app/Http/Presenters/StatusArrayPresenter.php
  api/app/Http/Presenters/UserArrayPresenter.php
  api/app/Repositories/EventType/EventTypeRepository.php
  client/src/components/event-types/EventTypesList.vue
  client/src/services/event-types/eventTypesService.js
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/eventTypes/getters.js
  client/src/store/modules/eventTypes/mutations.js
  client/src/store/modules/eventTypes/state.js
  client/src/store/modules/eventTypes/types/mutations.js
Labels: backend, enhancement, frontend

#243 Fix token expired error and localization
  client/src/router/index.js
  client/src/store/modules/auth/actions.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: frontend

#244 Feature/page with users event types
  client/src/components/public/users-event-types/UserEventType.vue
  client/src/views/UserEventTypesList.vue
Labels: frontend

#240 Create All Event types popup
  client/src/components/scheduled-events/Past/Filter/EventTypes.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/store/modules/scheduledEvent/actions.js
  client/src/store/modules/scheduledEvent/getters.js
  client/src/store/modules/scheduledEvent/mutations.js
  client/src/store/modules/scheduledEvent/state.js
  client/src/store/modules/scheduledEvent/types/actions.js
  client/src/store/modules/scheduledEvent/types/getters.js
  client/src/store/modules/scheduledEvent/types/mutations.js
Labels: frontend

#245 Fix/fix bg search input
  client/src/components/event-types/EventTypesList.vue
  client/src/store/modules/i18n/uk.js
Labels: fix, frontend

#250 Fix/update event type dropdown
  client/src/components/event-types/all-event-types/DropDown.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: fix, frontend

#251 Feature/custom field
  api/app/Entity/CustomField.php
  api/app/Entity/CustomFieldValue.php
  api/app/Entity/EventType.php
  api/database/migrations/2020_08_27_085128_create_custom_fields_table.php
  api/database/migrations/2020_08_27_085359_create_custom_field_values_table.php
Labels: backend

#249 Fix/event types list nickname
  client/src/components/event-types/all-event-types/ActionBlock.vue
Labels: fix, frontend

#246 Fix/load more btn
  client/src/components/event-types/EventTypesList.vue
Labels: fix, frontend

#254 Feature/googlecalandar integration
  api/.env.example
  api/app/Actions/SocialAccount/AuthAction.php
  api/app/Actions/SocialAccount/AuthResponse.php
  api/app/Actions/SocialAccount/GetCalendarsCollectionAction.php
  api/app/Actions/SocialAccount/GetCalendarsCollectionRequest.php
  api/app/Contracts/CalendarService.php
  api/app/Contracts/SocialAccountService.php
  api/app/Entity/SocialAccount.php
  api/app/Entity/User.php
  api/app/Http/Controllers/Api/SocialAccountController.php
  api/app/Http/Presenters/GoogleResponseArrayPresenter.php
  api/app/Http/Presenters/SocialAccountArrayPresenter.php
  api/app/Listeners/AddEventToGoogleCalendar.php
  api/app/Providers/AppServiceProvider.php
  api/app/Providers/EventServiceProvider.php
  api/app/Repositories/SocialAccount/Criterion/ProviderCriterion.php
  api/app/Repositories/SocialAccount/Criterion/UserCriterion.php
  api/app/Repositories/SocialAccount/SocialAccountRepository.php
  api/app/Repositories/SocialAccount/SocialAccountRepositoryInterface.php
  api/app/Services/Calendar/Google/GoogleCalendarEvent.php
  api/app/Services/SocialAccount/Google.php
  api/composer.json
  api/composer.lock
  api/config/services.php
  api/routes/api.php
  client/src/components/calendar-connections/CalendarDetails.vue
  client/src/components/calendar-connections/CalendarsList.vue
  client/src/components/calendar-connections/ConnectedList.vue
  client/src/services/connectedCalendars/calendarService.js
  client/src/services/socialAccount/socialAccountService.js
  client/src/store/index.js
  client/src/store/modules/connectedCalendars/actions.js
  client/src/store/modules/connectedCalendars/getters.js
  client/src/store/modules/connectedCalendars/index.js
  client/src/store/modules/connectedCalendars/mutations.js
  client/src/store/modules/connectedCalendars/state.js
  client/src/store/modules/connectedCalendars/types/getters.js
  client/src/store/modules/connectedCalendars/types/mutations.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: backend, enhancement

#255 Fix/load more btn
  client/src/components/event-types/EventTypesList.vue
Labels: fix, frontend

#257 Add upcoming scheduled events page
  client/src/components/scheduled-events/Upcoming/Upcoming.vue
Labels: frontend

#256 Fix height block
  client/src/views/UserEventTypesList.vue
Labels: fix, frontend

#253 Feature/custom field logic
  api/app/Actions/CustomField/AddCustomFieldsToEventTypeAction.php
  api/app/Actions/CustomField/AddCustomFieldsToEventTypeRequest.php
  api/app/Actions/CustomField/UpdateCustomFieldsToEventTypeAction.php
  api/app/Actions/CustomField/UpdateCustomFieldsToEventTypeRequest.php
  api/app/Actions/Event/AddEventAction.php
  api/app/Actions/Event/AddEventRequest.php
  api/app/Entity/CustomField.php
  api/app/Entity/Event.php
  api/app/Exceptions/Availability/WrongDateTimeException.php
  api/app/Exceptions/ErrorCode.php
  api/app/Http/Controllers/Api/EventController.php
  api/app/Http/Controllers/Api/EventTypeController.php
  api/app/Http/Requests/Api/CustomField/CustomFieldRequest.php
  api/app/Http/Requests/Api/CustomField/CustomFieldTypes.php
  api/app/Http/Requests/Api/Event/EventRequest.php
  api/app/Repositories/Event/EventRepository.php
  api/app/Repositories/Event/EventRepositoryInterface.php
  api/app/Repositories/EventType/EventTypeRepository.php
  api/app/Repositories/EventType/EventTypeRepositoryInterface.php
  api/app/Services/Availability/AvailabilityService.php
  api/database/migrations/2020_08_27_085128_create_custom_fields_table.php
  api/routes/api.php
  api/tests/Feature/AvailabilityService/AvailabilityServiceTest.php
Labels: backend

#258 Feature/scheduled events pagination
  client/src/components/scheduled-events/Pagination.vue
  client/src/components/scheduled-events/Past/Past.vue
  client/src/components/scheduled-events/Upcoming/Upcoming.vue
  client/src/services/scheduled-event/scheduledEventsService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/store/modules/scheduledEvent/actions.js
  client/src/store/modules/scheduledEvent/mutations.js
  client/src/store/modules/scheduledEvent/normalizer.js
  client/src/store/modules/scheduledEvent/state.js
  client/src/store/modules/scheduledEvent/types/mutations.js
Labels: frontend

#264 Fix creating event
  api/app/Actions/Event/AddEventAction.php
  api/app/Actions/Event/AddEventRequest.php
  api/app/Http/Requests/Api/Event/EventRequest.php
Labels: backend, hotfix

#265 Fix import in component
  client/src/components/events/CreateEventTypeForm.vue
Labels: frontend, hotfix

#262 Feature/shceduled events filter
  api/app/Actions/Event/GetEventsEmailsAction.php
  api/app/Actions/Event/GetEventsEmailsRequest.php
  api/app/Actions/Event/GetEventsEmailsResponse.php
  api/app/Actions/EventType/GetEventTypeCollectionAction.php
  api/app/Actions/EventType/GetEventTypeCollectionRequest.php
  api/app/Http/Controllers/Api/EventController.php
  api/app/Http/Controllers/Api/EventTypeController.php
  api/app/Http/Presenters/EventsEmailsPresenter.php
  api/app/Repositories/Event/EventRepository.php
  api/app/Repositories/EventType/EventTypeRepository.php
  api/routes/api.php
  client/src/components/scheduled-events/FilterButton.vue
  client/src/components/scheduled-events/Pagination.vue
  client/src/components/scheduled-events/Past/Filter/EventTypes.vue
  client/src/components/scheduled-events/Past/Filter/FilterList.vue
  client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
  client/src/components/scheduled-events/Past/Past.vue
  client/src/components/scheduled-events/Pending/Pending.vue
  client/src/components/scheduled-events/Upcoming/Upcoming.vue
  client/src/router/index.js
  client/src/services/event-types/eventTypesService.js
  client/src/services/scheduled-event/scheduledEventsService.js
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/store/modules/scheduledEvent/state.js
Labels: backend, frontend

#266 Add nickname to normalizer
  client/src/store/modules/eventType/normalizer.js
Labels: frontend, hotfix

#268 Fix link
  client/src/components/public/users-event-types/UserEventType.vue
  client/src/views/UserEventTypesList.vue
Labels: frontend, hotfix

#276 Fix nickname
  api/app/Actions/Auth/RegisterAction.php
Labels: backend, fix

#277 Add email to invitee
  api/app/Listeners/SendEventCreatedNotificationToInvitee.php
  api/app/Listeners/SendEventCreatedNotificationToOwner.php
  api/app/Mail/EventCreatedMailToInvitee.php
  api/app/Mail/EventCreatedMailToOwner.php
  api/app/Notifications/EventCreatedNotification.php
  api/app/Providers/EventServiceProvider.php
  api/resources/views/emails/event_created_to_invitee.blade.php
Labels: backend

#275 Fix public page with users EventTypes
  api/app/Actions/EventType/GetEventTypeCollectionByNicknameAction.php
  api/app/Actions/EventType/GetEventTypeCollectionByNicknameResponse.php
  api/app/Http/Controllers/Api/EventTypeController.php
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/eventTypes/getters.js
  client/src/store/modules/eventTypes/mutations.js
  client/src/store/modules/eventTypes/state.js
  client/src/store/modules/eventTypes/types/getters.js
  client/src/store/modules/eventTypes/types/mutations.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/views/UserEventTypesList.vue
Labels: backend, fix, frontend

#278 Feature/elastic search
  .github/workflows/testing.yml
  api/.env.example
  api/README.md
  api/app/Actions/Event/AddEventAction.php
  api/app/Aggregates/Events/EventAggregate.php
  api/app/Events/EventCreated.php
  api/app/Listeners/AddEventToElasticSearch.php
  api/app/Providers/AppServiceProvider.php
  api/app/Providers/EventServiceProvider.php
  api/app/Repositories/ElasticSearch/Events/ElasticsearchEventAggregateRepository.php
  api/app/Repositories/ElasticSearch/Events/EventAggregateRepositoryInterface.php
  api/composer.json
  api/composer.lock
  api/docker-compose.override.yml.example
  api/phpunit.github.xml
  api/tests/Feature/AvailabilityService/AvailabilityServiceTest.php
  api/tests/Feature/CustomField/CustomFieldTest.php
Labels: backend

#280 Feature/scheduled events emails filter
  api/app/Actions/Event/GetEventCollectionAction.php
  api/app/Actions/Event/GetEventCollectionRequest.php
  api/app/Actions/Event/GetEventsEmailsAction.php
  api/app/Actions/Event/GetEventsEmailsRequest.php
  api/app/Http/Controllers/Api/EventController.php
  api/app/Http/Presenters/EventsEmailsPresenter.php
  api/app/Repositories/Event/Criterion/EmailsNameCriterion.php
  api/app/Repositories/Event/Criterion/EventEmailsCriterion.php
  api/app/Repositories/Event/Criterion/EventStatusCriterion.php
  client/src/assets/images/no-found.svg
  client/src/components/scheduled-events/FilterButton.vue
  client/src/components/scheduled-events/NoEvents.vue
  client/src/components/scheduled-events/Past/Filter/EventTypes.vue
  client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
  client/src/components/scheduled-events/Past/Filter/Status.vue
  client/src/components/scheduled-events/Past/Past.vue
  client/src/services/scheduled-event/scheduledEventsService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/store/modules/scheduledEvent/actions.js
  client/src/store/modules/scheduledEvent/getters.js
  client/src/store/modules/scheduledEvent/mutations.js
  client/src/store/modules/scheduledEvent/normalizer.js
  client/src/store/modules/scheduledEvent/state.js
  client/src/store/modules/scheduledEvent/types/actions.js
  client/src/store/modules/scheduledEvent/types/getters.js
  client/src/store/modules/scheduledEvent/types/mutations.js
Labels: backend, frontend

#283 Add copy functionality
  client/src/components/event-types/all-event-types/EventType.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: enhancement, frontend

#282 Feature/tags endpoint
  api/app/Actions/Tag/GetTagsByEventDateRangeAction.php
  api/app/Actions/Tag/GetTagsByEventDateRangeRequest.php
  api/app/Actions/Tag/GetTagsByEventTypeIdAction.php
  api/app/Actions/Tag/GetTagsByEventTypeIdRequest.php
  api/app/Actions/Tag/GetTagsResponse.php
  api/app/Entity/EventType.php
  api/app/Entity/Tag.php
  api/app/Http/Controllers/Api/TagController.php
  api/app/Http/Presenters/TagPresenter.php
  api/app/Providers/AppServiceProvider.php
  api/app/Repositories/Tag/Criterion/EndDateCriterion.php
  api/app/Repositories/Tag/Criterion/EventTypeIdCriterion.php
  api/app/Repositories/Tag/Criterion/StartDateCriterion.php
  api/app/Repositories/Tag/TagRepository.php
  api/app/Repositories/Tag/TagRepositoryInterface.php
  api/database/factories/TagFactory.php
  api/database/migrations/2020_08_31_055946_create_tags_table.php
  api/database/seeds/DatabaseSeeder.php
  api/database/seeds/TagsSeeder.php
  api/routes/api.php
Labels: backend

#287 Fix load more btn displaying
  client/src/components/event-types/EventTypesList.vue
  client/src/services/event-types/eventTypesService.js
  client/src/store/modules/eventTypes/actions.js
Labels: fix, frontend

#261 Feature/google auth calendar response
  api/.env.example
  api/app/Actions/SocialAccount/AuthAction.php
  api/app/Actions/SocialAccount/AuthResponse.php
  api/app/Contracts/CalendarEventInterface.php
  api/app/Contracts/CalendarService.php
  api/app/Entity/SocialAccount.php
  api/app/Exceptions/ErrorCode.php
  api/app/Exceptions/GoogleOauthException.php
  api/app/Http/Controllers/Api/SocialAccountController.php
  api/app/Listeners/AddEventToGoogleCalendar.php
  api/app/Providers/EventServiceProvider.php
  api/app/Repositories/SocialAccount/SocialAccountRepository.php
  api/app/Repositories/SocialAccount/SocialAccountRepositoryInterface.php
  api/app/Services/Calendar/Google/GoogleCalendarEvent.php
  api/app/Services/Calendar/Google/GoogleCalendarEventPresenter.php
  api/app/Services/SocialAccount/Google.php
  api/config/services.php
  client/src/components/calendar-connections/CalendarsList.vue
Labels: backend, enhancement

#288 Create add teg action, route, controller, request, response
  api/app/Actions/Tag/AddTagAction.php
  api/app/Actions/Tag/AddTagRequest.php
  api/app/Actions/Tag/AddTagResponse.php
  api/app/Http/Controllers/Api/TagController.php
  api/app/Http/Requests/Api/Tag/TagRequest.php
  api/app/Repositories/Tag/TagRepository.php
  api/app/Repositories/Tag/TagRepositoryInterface.php
  api/routes/api.php
Labels: backend
