Repository BinaryStudioAcademy/bsa-2020-schedulia, pull requests merged in 2020-09, with the labels that each got.

#286 Feature/internal note
  api/app/Actions/EventType/UpdateInternalNoteByIdAction.php
  api/app/Actions/EventType/UpdateInternalNoteByIdRequest.php
  api/app/Entity/EventType.php
  api/app/Http/Controllers/Api/EventTypeController.php
  api/app/Http/Presenters/EventTypePresenter.php
  api/database/migrations/2020_08_31_131116_add_internal_note_field_to_event_types_table.php
  api/routes/api.php
  client/src/components/event-types/all-event-types/AddInternalNoteDialog.vue
  client/src/components/event-types/all-event-types/DropDown.vue
  client/src/components/event-types/all-event-types/EventType.vue
  client/src/services/event-types/eventTypesService.js
  client/src/store/modules/eventType/normalizer.js
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/eventTypes/mutations.js
  client/src/store/modules/eventTypes/types/actions.js
  client/src/store/modules/eventTypes/types/mutations.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: backend, enhancement, frontend

#294 disconetc calendar action
  api/app/Actions/SocialAccount/DeleteCalendarAccountAction.php
  api/app/Actions/SocialAccount/DeleteCalendarRequest.php
  api/app/Contracts/SocialAccountService.php
  api/app/Entity/SocialAccount.php
  api/app/Exceptions/SocialAccount/SocialAccountNotFoundException.php
  api/app/Http/Controllers/Api/SocialAccountController.php
  api/app/Repositories/SocialAccount/SocialAccountRepository.php
  api/app/Services/SocialAccount/Google.php
  api/routes/api.php
Labels: backend

#297 Feature/scheduled events search input
  api/app/Actions/Event/GetEventCollectionAction.php
  api/app/Actions/Event/GetEventCollectionRequest.php
  api/app/Http/Controllers/Api/EventController.php
  api/app/Repositories/Event/Criterion/SearchStringCriterion.php
  client/src/components/scheduled-events/FilterButton.vue
  client/src/components/scheduled-events/Past/Filter/EventTypes.vue
  client/src/components/scheduled-events/Past/Filter/EventTypesTags.vue
  client/src/components/scheduled-events/Past/Filter/FilterList.vue
  client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
  client/src/components/scheduled-events/Past/Filter/Status.vue
  client/src/components/scheduled-events/Past/Filter/Teams.vue
  client/src/components/scheduled-events/Past/Filter/TrackingId.vue
  client/src/components/scheduled-events/Past/Past.vue
  client/src/components/scheduled-events/SearchInput.vue
  client/src/components/scheduled-events/TabsButton.vue
  client/src/services/scheduled-event/scheduledEventsService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/store/modules/scheduledEvent/actions.js
Labels: backend, frontend

#295 disconect calendars
  client/src/components/calendar-connections/CalendarDetails.vue
  client/src/components/calendar-connections/ConnectedList.vue
  client/src/services/connectedCalendars/calendarService.js
  client/src/store/modules/connectedCalendars/actions.js
  client/src/store/modules/connectedCalendars/mutations.js
  client/src/store/modules/connectedCalendars/types/mutations.js
Labels: enhancement, frontend

#291 Feature/get time according timezone
  api/app/Entity/Event.php
  api/app/Listeners/AddEventToGoogleCalendar.php
  api/app/Repositories/User/UserRepository.php
  api/app/Services/Calendar/Google/GoogleCalendarColors.php
  api/app/Services/Calendar/Google/GoogleCalendarEvent.php
  api/app/Services/Calendar/Google/GoogleCalendarEventPresenter.php
  api/app/Services/SocialAccount/Google.php
Labels: backend

#299 Add Unavailable type for Availability
  api/app/Actions/AvailabilityService/ModificateDateTimeListRequest.php
  api/app/Actions/AvailabilityService/ProcessUnavailableDatesAction.php
  api/app/Services/Availability/AvailabilityService.php
  api/app/Services/Availability/AvailabilityTypes.php
  client/src/components/event-types/EventTypesList.vue
  client/src/components/event-types/all-event-types/DropDown.vue
  client/src/components/events/CreateEventTypeBookingForm.vue
  client/src/components/events/custom-fields/CreateEventTypeQuestions.vue
  client/src/components/loader/Loader.vue
  client/src/store/modules/eventTypes/actions.js
  client/src/views/NewEventTypeAdditionalOptions.vue
Labels: backend, enhancement

#298 Fix route
  api/app/Actions/EventType/GetEventTypeByIdAndOwnerNicknameAction.php
  api/app/Actions/EventType/GetEventTypeByIdAndOwnerNicknameRequest.php
  api/app/Actions/EventType/GetEventTypeByIdAndOwnerNicknameResponse.php
  api/app/Exceptions/EventTypeNotFoundException.php
  api/app/Http/Controllers/Api/EventTypeController.php
  api/app/Repositories/EventType/Criterion/IdCriterion.php
  api/app/Repositories/EventType/EventTypeRepository.php
  api/app/Repositories/EventType/EventTypeRepositoryInterface.php
  api/routes/api.php
  client/src/components/public/calendar/EventType.vue
  client/src/services/public-event/publicEventService.js
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/publicEvent/actions.js
Labels: backend

#301 Feature/location field to entity
  api/app/Actions/EventType/AddEventTypeAction.php
  api/app/Actions/EventType/AddEventTypeRequest.php
  api/app/Actions/EventType/UpdateEventTypeAction.php
  api/app/Actions/EventType/UpdateEventTypeRequest.php
  api/app/Entity/EventType.php
  api/app/Exceptions/ErrorCode.php
  api/app/Exceptions/EventType/CoordinatesFieldIsRequiredException.php
  api/app/Http/Controllers/Api/EventTypeController.php
  api/app/Http/Presenters/EventTypePresenter.php
  api/app/Http/Requests/Api/EventType/EventTypeRequest.php
  api/app/Http/Requests/Api/EventType/LocationTypes.php
  api/database/migrations/2020_09_01_200527_add_location_field_to_event_types_table.php
  api/tests/Feature/AvailabilityService/AvailabilityServiceTest.php
  api/tests/Feature/CustomField/CustomFieldTest.php
  api/tests/Feature/EventType/EventTypeApiTest.php
Labels: backend

#304 fix typo in uri
  client/src/services/connectedCalendars/calendarService.js
Labels: bug, frontend

#306 Feature/search scheduled events elasticsearch
  api/app/Actions/Event/GetEventCollectionAction.php
  api/app/Aggregates/Events/EventAggregate.php
  api/app/Contracts/ElasticSearchCriterion.php
  api/app/DataTransformer/Events/EventFlowCollection.php
  api/app/DataTransformer/Events/ParameterFlowCollection.php
  api/app/Entity/Event.php
  api/app/Http/Presenters/EventPresenter.php
  api/app/Repositories/ElasticSearch/Events/Criterion/EndDateCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/EventEmailsCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/EventStatusCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/EventTypesCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/OwnerCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/SearchStringCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/StartDateCriterion.php
  api/app/Repositories/ElasticSearch/Events/ElasticsearchEventAggregateRepository.php
  api/app/Repositories/ElasticSearch/Events/EventAggregateRepositoryInterface.php
Labels: backend

#303 Feature/slack integration
  api/app/Actions/Slack/AddSlackNotificationsAction.php
  api/app/Actions/Slack/AddSlackNotificationsRequest.php
  api/app/Actions/Slack/ChangeActivitySlackNotificationsAction.php
  api/app/Actions/Slack/ChangeActivitySlackNotificationsRequest.php
  api/app/Actions/Slack/DeleteSlackNotificationsAction.php
  api/app/Entity/User.php
  api/app/Http/Controllers/Api/SlackController.php
  api/app/Http/Requests/Api/Slack/SlackChangeActivityRequest.php
  api/app/Http/Requests/Api/Slack/SlackRequest.php
  api/app/Notifications/EventCreatedNotification.php
  api/app/Notifications/SlackMessages/EventCreatedSlackMessage.php
  api/composer.json
  api/composer.lock
  api/database/migrations/2020_09_02_183643_add_slack_hook_to_users_table.php
  api/routes/api.php
Labels: backend

#308 Hotfix/show upcoming events
  api/app/Http/Controllers/Api/EventController.php
  client/src/store/modules/scheduledEvent/actions.js
Labels: backend, bug, frontend

#309 Hotfix/delete elasticksearch index command
  api/app/Console/Commands/DeleteIndexCommand.php
  api/app/Console/Commands/ReindexCommand.php
  api/app/Repositories/ElasticSearch/Events/ElasticsearchEventAggregateRepository.php
  api/app/Repositories/ElasticSearch/Events/EventAggregateRepositoryInterface.php
Labels: hotfix

#316 Fix route
  client/src/components/events/CreateEventTypeBookingForm.vue
Labels: fix

#314 Feature/cancel scheduled event frontend
  api/app/Actions/Event/UpdateEventAction.php
  api/app/Actions/Event/UpdateEventRequest.php
  api/app/Http/Controllers/Api/EventController.php
  api/app/Http/Presenters/EventPresenter.php
  api/app/Http/Requests/Api/Event/UpdateEventRequest.php
  client/src/components/confirm/ConfirmDialog.vue
  client/src/components/scheduled-events/Event.vue
  client/src/services/scheduled-event/scheduledEventsService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/store/modules/scheduledEvent/actions.js
  client/src/store/modules/scheduledEvent/mutations.js
  client/src/store/modules/scheduledEvent/normalizer.js
  client/src/store/modules/scheduledEvent/types/actions.js
  client/src/store/modules/scheduledEvent/types/mutations.js
  client/src/store/modules/scheduledEvent/types/statuses.js
Labels: backend, enhancement, frontend

#321 remove edit, invite again etc from cancelled event
  client/src/components/scheduled-events/Event.vue
Labels: frontend

#325 Clear customFields in state after creating them
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/eventTypes/mutations.js
  client/src/store/modules/eventTypes/types/mutations.js
Labels: fix, frontend

#312 Feature/slack integration
  api/app/Http/Presenters/UserArrayPresenter.php
  client/src/components/common/GeneralLayout/UserMenu.vue
  client/src/components/notification-connections/chatito/ChatitoNotificationConnection.vue
  client/src/components/notification-connections/slack/DeleteSlackIntegrationModal.vue
  client/src/components/notification-connections/slack/SlackModalIntegrationConnect.vue
  client/src/components/notification-connections/slack/SlackNotificationConnection.vue
  client/src/router/index.js
  client/src/services/notification-connections/notificationConnectionService.js
  client/src/store/modules/auth/actions.js
  client/src/store/modules/auth/mutations.js
  client/src/store/modules/auth/types/actions.js
  client/src/store/modules/auth/types/mutations.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/views/NotificationConnections.vue
Labels: frontend

#327 Delete relations
  api/app/Actions/EventType/DeleteEventTypeAction.php
Labels: backend, fix

#329 Fix router push
  client/src/components/events/CreateEventTypeBookingForm.vue
Labels: fix, frontend

#317 Filter events
  api/app/Actions/AvailabilityService/ProcessUnavailableTimeAction.php
  api/app/Entity/EventType.php
Labels: backend, fix

#330 Hotfix/scheduled events page
  api/app/Repositories/ElasticSearch/Events/Criterion/EndDateCriterion.php
  client/src/components/scheduled-events/DatePickerTab.vue
  client/src/components/scheduled-events/DateRange/DateRange.vue
  client/src/components/scheduled-events/DateRangeScheduledEventsList.vue
  client/src/components/scheduled-events/Event.vue
  client/src/components/scheduled-events/Past/Past.vue
  client/src/components/scheduled-events/PastScheduledEventsList.vue
  client/src/components/scheduled-events/Upcoming/Upcoming.vue
  client/src/components/scheduled-events/UpcomingScheduledEventsList.vue
Labels: hotfix

#333 Fix sorting
  api/app/Http/Presenters/EventTypePresenter.php
  api/app/Repositories/EventType/EventTypeRepository.php
  client/src/store/modules/eventType/normalizer.js
  client/src/store/modules/eventTypes/getters.js
Labels: backend, frontend, hotfix

#335 Add ES events update method
  api/app/Listeners/UpdateEventToElasticSearch.php
  api/app/Providers/EventServiceProvider.php
  api/app/Repositories/ElasticSearch/Events/ElasticsearchEventAggregateRepository.php
  api/app/Repositories/ElasticSearch/Events/EventAggregateRepositoryInterface.php
Labels: hotfix

#332 Add custom_fields to mail if exist
  api/app/Mail/EventCreatedMailToInvitee.php
  api/app/Mail/EventCreatedMailToOwner.php
  api/resources/views/emails/event_created_to_invitee.blade.php
  api/resources/views/notifications/event_created.blade.php
Labels: backend, fix

#345 Fix/event types state refresh
  api/app/Http/Requests/Api/EventType/EventTypeRequest.php
  client/src/components/event-types/all-event-types/ActionBlock.vue
  client/src/store/modules/eventType/actions.js
  client/src/store/modules/eventType/mutations.js
  client/src/store/modules/eventType/normalizer.js
  client/src/store/modules/eventType/types/actions.js
  client/src/store/modules/eventType/types/mutations.js
Labels: fix

#352 Fix blinking
  client/src/components/event-types/EventTypesList.vue
  client/src/store/modules/eventTypes/actions.js
  client/src/store/modules/eventTypes/types/actions.js
Labels: fix, frontend

#353 Fix/tags endpoint
  api/app/Http/Controllers/Api/TagController.php
  api/app/Http/Requests/Api/EventType/EventTypeRequest.php
  api/app/Http/Requests/Api/Tag/TagRequest.php
  api/app/Repositories/Tag/Criterion/EventTypeIdCriterion.php
Labels: backend, fix

#365 fixed 12/24h format saving in profile
  client/src/components/profile/ProfileForm.vue
  client/src/components/profile/ProfileSelect.vue
Labels: bug

#370 Fix/shoe error on event create
  api/app/Actions/Event/AddEventAction.php
  api/app/Http/Controllers/Api/EventController.php
  api/tests/Feature/AvailabilityService/AvailabilityServiceTest.php
  api/tests/Feature/CustomField/CustomFieldTest.php
  client/src/components/calendar-connections/CalendarsList.vue
  client/src/components/public/calendar/ConfirmEventType.vue
  client/src/store/modules/publicEvent/actions.js
Labels: backend, bug, frontend

#384 branding fix profile
  api/app/Actions/Upload/DeleteImageAction.php
  api/app/Actions/Upload/DeleteImageRequest.php
  api/app/Http/Controllers/Api/UploadController.php
  api/routes/api.php
  client/src/components/profile/BrandingForm.vue
  client/src/components/profile/ProfileForm.vue
  client/src/services/upload/fileService.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/profile/actions.js
Labels: bug

#386 Fix/scheduled events past upcoming date range
  api/app/Actions/Event/GetEventCollectionAction.php
  api/app/Repositories/ElasticSearch/Events/Criterion/TagsCriterion.php
  client/src/components/scheduled-events/DateRange/DateRange.vue
  client/src/components/scheduled-events/Upcoming/Filter/EventTypesTags.vue
  client/src/components/scheduled-events/Upcoming/Upcoming.vue
  client/src/store/modules/scheduledEvent/getters.js
  client/src/store/modules/scheduledEvent/mutations.js
  client/src/store/modules/scheduledEvent/state.js
Labels: frontend

#390 Fix/scheduled events past upcoming date range
  api/app/Repositories/ElasticSearch/Events/Criterion/EventEmailsCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/SearchStringCriterion.php
  api/app/Repositories/ElasticSearch/Events/Criterion/TagsCriterion.php
  api/app/Repositories/ElasticSearch/Events/ElasticsearchEventAggregateRepository.php
  client/src/components/scheduled-events/Upcoming/Filter/InviteeEmails.vue
Labels: backend

#392 Fix pagination
  client/src/components/scheduled-events/Pagination.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: fix, frontend

#394 Feature/scheduled events tags in events card
  client/src/components/events/CreateEventTypeForm.vue
  client/src/components/scheduled-events/Event.vue
  client/src/store/modules/eventType/normalizer.js
  client/src/store/modules/eventType/state.js
Labels: frontend

#408 Hotfix/scheduled events layout
  client/src/components/common/GeneralLayout/GeneralLayout.vue
  client/src/components/scheduled-events/DateRange/DateRange.vue
  client/src/components/scheduled-events/DateRange/Filter/EventTypesTags.vue
  client/src/components/scheduled-events/Past/Filter/EventTypesTags.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: hotfix

#411 add google exception
  api/app/Services/SocialAccount/Google.php
Labels: bug

#413 Fix messages
  api/app/Mail/EventCreatedMailToInvitee.php
  api/app/Mail/EventCreatedMailToOwner.php
  api/app/Notifications/Chatito/EventCreatedChatitoMessage.php
  api/resources/views/emails/event_created_to_invitee.blade.php
  api/resources/views/notifications/event_created.blade.php
Labels: hotfix

#416 Fix/cancelled scheduled event
  client/src/store/modules/scheduledEvent/normalizer.js
Labels: fix

#428 Feature/event type tag validation
  client/src/components/events/CreateEventTypeForm.vue
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
Labels: frontend

#431 Fix problem with search input
  client/src/components/scheduled-events/DateRange/Filter/SearchInput.vue
  client/src/components/scheduled-events/Past/Filter/SearchInput.vue
  client/src/components/scheduled-events/Upcoming/Filter/SearchInput.vue
Labels: fix, frontend

#433 add validation to welcome field
  client/src/components/profile/ProfileForm.vue
  client/src/components/profile/ProfileTextArea.vue
Labels: bug

#434 branding image size
  client/src/components/profile/BrandingForm.vue
Labels: bug

#432 Fix/lang
  client/src/store/modules/i18n/uk.js
Labels: fix

#435 Fix/scheduled event custom fields
  api/app/Aggregates/Events/EventAggregate.php
  api/app/Http/Presenters/EventTypePresenter.php
  client/src/components/scheduled-events/Event.vue
  client/src/store/modules/eventType/normalizer.js
  client/src/store/modules/scheduledEvent/normalizer.js
Labels: backend, fix, frontend

#437 Fix/scheduled events time
  client/src/components/scheduled-events/Event.vue
Labels: fix, frontend

#440 Addon/image size validator
  client/src/assets/images/no-image.png
  client/src/components/profile/BrandingForm.vue
  client/src/components/profile/ProfileForm.vue
  client/src/config/file.js
  client/src/store/modules/i18n/en.js
  client/src/store/modules/i18n/uk.js
  client/src/validators/filesize.js
Labels: enhancement

#446 Fix
  client/src/components/scheduled-events/Event.vue
Labels: hotfix
